### ISSUE TITLE
Update VcMod

### ISSUE THREAD

**Issue by Segeco** [LouisK130/Orange-Cosmos-Roleplay#47] opened 2016-08-19 14:39 UTC
Can you update VcMod to the latest?

**Comment by MrManlyPrincess** [comment] 2016-08-22 17:12
I second this notion, it would be fantastic to be able to use the most up-to-date features.
Even just some guidance on how to do this would be great.

Thanks.

**Comment by LouisK130** [comment] 2016-08-22 18:11
Unfortunately I don't have time to look into how OCRP could support newer versions of VCMod. The issue is that this gamemode relies on some modifications to core VCMod files. In all newer versions of VCMod, the code is streamed from an external server each time the server launches, meaning it's not possible to make local changes.

If anyone is interested in experimenting with modifying VCMod's streamed code or removing the neccesity for modification at all, here's a list of the changes that I made to VCMod files for OCRP. Sorry that they aren't very specific, they were just quick notes to myself so that I wouldn't forget what I changed while developing.

http://puu.sh/qKvbT/a998824303.png

**Comment by Segeco** [comment] 2016-08-22 19:53
Just to update, the VcMod versions you sent no longer work. Content errors and anyone can unlock cars. Skins dont work on car purchase etc.

**Comment by MrManlyPrincess** [comment] 2016-08-22 20:37
I did experience the content errors, but have not experienced any locking or skin issues.
Content errors were fixed by a couple addons from the workshop.

**Comment by Segeco** [comment] 2016-08-23 23:08
Could you notify me please of the content?

**Closed as completed** 2016-12-01 16:15 UTC
