### ISSUE TITLE
Making RP names show up instead of Steam names

### ISSUE THREAD

**Issue by clunkyy** [LouisK130/Orange-Cosmos-Roleplay#60] opened 2016-11-27 20:53 UTC
Why does this use steam names instead of RP names

**Comment by LouisK130** [comment] 2016-11-27 22:27
I never much cared for RP names. It shouldn't be too difficult to add yourself or find someone who is willing to. Check out client/hud.lua for name drawing.

**Comment by LouisK130** [comment] 2016-11-27 22:28
Duplicate of #42

**Closed as completed by LouisK130** 2016-11-27 22:28 UTC
